commentAfterEqual.c:1:1: keyword int
commentAfterEqual.c:1:5: identifier main
commentAfterEqual.c:1:9: punctuator (
commentAfterEqual.c:1:10: keyword int
commentAfterEqual.c:1:14: identifier argc
commentAfterEqual.c:1:18: punctuator ,
commentAfterEqual.c:1:20: keyword char
commentAfterEqual.c:1:24: punctuator *
commentAfterEqual.c:1:26: identifier argv
commentAfterEqual.c:1:30: punctuator [
commentAfterEqual.c:1:31: punctuator ]
commentAfterEqual.c:1:32: punctuator )
commentAfterEqual.c:1:34: punctuator {
commentAfterEqual.c:2:2: keyword char
commentAfterEqual.c:2:6: punctuator *
commentAfterEqual.c:2:8: identifier text
commentAfterEqual.c:2:13: punctuator =
commentAfterEqual.c:2:15: stringliteral "hihoha"
commentAfterEqual.c:2:23: punctuator ;
commentAfterEqual.c:3:2: keyword char
commentAfterEqual.c:3:7: identifier t
commentAfterEqual.c:3:9: punctuator =
commentAfterEqual.c:3:9: punctuator =
commentAfterEqual.c:3:39: constant 'o'
commentAfterEqual.c:3:42: punctuator ;
commentAfterEqual.c:4:2: keyword return
commentAfterEqual.c:4:9: constant 0
commentAfterEqual.c:4:10: punctuator ;
commentAfterEqual.c:5:1: punctuator }
